[pytest]
addopts = -v --html=reports/sp_automation_report.html --self-contained-html
pythonpath = .
python_files = test_*.py
norecursedirs = tests/helpers
# suppress collection warnings for enums or other classes with custom __new__
filterwarnings =
    ignore::pytest.PytestCollectionWarning
