[pytest]
python_files = test_*.py
norecursedirs = tests/helpers
# suppress collection warnings for enums or other classes with custom __new__
filterwarnings =
    ignore::pytest.PytestCollectionWarning
